#!/bin/bash

set -euxo pipefail

BEELINER_LINK="https://github.com/Willamin/beeline/releases/download/v0.2.0/beeliner.tar.gz"
BEELINER_TAR_NAME="beeliner.tar.gz"
BEELINER_NAME="beeliner"
TEMP="/tmp/beeline-installer"
cd TEMP
curl -s BEELINER_LINK -o BEELINER_TAR_NAME

tar xzf BEELINER_TAR_NAME
chmod +x BEELINER_NAME
$(BEELINER_NAME)

echo -n "Want to remove the installation guide? (y/n) "
read answer
if echo "$answer" | grep -iq "^y" ;then
    echo "Removing the guide..."
    rm -rf $TEMP
    echo "Done!"
else
    echo "The installation guide is here: $TEMP/$BEELINER_NAME"
    echo "I'd recommend you move it somewhere more easily accessible."
fi

echo ""
echo "I hope you enjoy Beeline! Have a nice day!"
